version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: datatables
      MYSQL_USER: testacc
      MYSQL_PASSWORD: password123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080